/**
 * Browser-side mirror of `crates/oximemo-core/src/tasks.rs::transform_task_draft`
 * (Plan C Task 1). The Rust kernel is the source of truth; this file
 * reproduces enough of it — one-line scanner, splice, terminal
 * transitions, recurrence spawn, CRLF preservation — for the CM6 editor
 * to apply edits to its unsaved buffer without round-tripping through
 * Tauri's IPC for every keystroke. Output is verified byte-for-byte
 * against `taskFixtures.json` (regenerated by
 * `crates/oximemo-core/src/tasks.rs::emit_golden_fixture_corpus` under
 * `UPDATE_TASK_FIXTURES=1`).
 *
 * Deliberately does not import any Tauri types (the mirror ships before
 * the wire types exist) and does not model `TaskEdit::Delete` — the spec
 * defers that to a later task and Tasks 2/8/9/10 don't need it.
 */

// --- Public types (mirrored; match the brief exactly) -------------------

export type TaskField =
  | "created"
  | "start"
  | "scheduled"
  | "due"
  | "done"
  | "cancelled"
  | "priority"
  | "recurrence";

export type DateField = Exclude<TaskField, "priority" | "recurrence">;

export type Priority =
  | "highest"
  | "high"
  | "medium"
  | "low"
  | "lowest"
  | null;

export type WriteFormat = "emoji" | "dataview";

export type RecurrenceInsert = "above" | "below";

export type StatusType =
  | "TODO"
  | "IN_PROGRESS"
  | "ON_HOLD"
  | "DONE"
  | "CANCELLED"
  | "NON_TASK";

export interface StatusDef {
  symbol: string;
  type: StatusType;
  next: string;
}

export interface TaskLineCfg {
  writeFormat: WriteFormat;
  globalFilter: string;
  recurrenceInsert: RecurrenceInsert;
  statuses: StatusDef[];
}

export type TaskEdit =
  | { kind: "toggle" }
  | { kind: "status"; symbol: string }
  | { kind: "date"; field: DateField; value: string | null }
  | { kind: "priority"; value: Priority }
  | { kind: "text"; value: string }
  | { kind: "recurrence"; value: string | null };

// Wire shape matches the Rust `TaskLineChange` serialized as
// snake_case (the kernel struct has no `Serialize` derive, so the
// emitter hand-builds the JSON with the same field names Rust uses).
export interface TaskLineChange {
  start_line: number;
  delete_lines: number;
  insert_lines: string[];
}

export interface TaskDraftTransformJson {
  changes: TaskLineChange[];
}

export interface FieldSpan {
  field: TaskField;
  start: number;
  end: number;
}

export interface ParsedLine {
  symbol: string;
  statusType: StatusType;
  text: string;
  spans: { checkbox: { start: number; end: number }; fields: FieldSpan[] };
}

interface StatusEntry {
  next: string;
  type: StatusType;
}

const BUILTIN_STATUSES: StatusDef[] = [
  { symbol: " ", type: "TODO", next: "x" },
  { symbol: "/", type: "IN_PROGRESS", next: "x" },
  { symbol: "x", type: "DONE", next: " " },
  { symbol: "-", type: "CANCELLED", next: " " },
];

function buildStatusTable(defs: StatusDef[]): Map<string, StatusEntry> {
  const map = new Map<string, StatusEntry>();
  for (const def of BUILTIN_STATUSES) {
    const sym = def.symbol === "X" ? "x" : def.symbol;
    map.set(sym, { next: def.next, type: def.type });
  }
  for (const def of defs) {
    const sym = def.symbol === "X" ? "x" : def.symbol;
    map.set(sym, { next: def.next, type: def.type });
  }
  return map;
}

// --- Emoji constants ----------------------------------------------------

const EMOJI_CREATED = "➕";
const EMOJI_START = "🛫";
const EMOJI_SCHEDULED = "⏳";
const EMOJI_DUE = "📅";
const EMOJI_DONE = "✅";
const EMOJI_CANCELLED = "❌";
const EMOJI_RECURRENCE = "🔁";
const VARIATION_SELECTOR_16 = "\u{FE0F}";
const NBSP = "\u{00A0}";

const DATE_EMOJI_TO_FIELD: Record<string, TaskField> = {
  [EMOJI_CREATED]: "created",
  [EMOJI_START]: "start",
  [EMOJI_SCHEDULED]: "scheduled",
  [EMOJI_DUE]: "due",
  [EMOJI_DONE]: "done",
  [EMOJI_CANCELLED]: "cancelled",
};

const PRIORITY_EMOJI: Record<string, Priority> = {
  "🔺": "highest",
  "⏫": "high",
  "🔼": "medium",
  "🔽": "low",
  "⏬": "lowest",
};

const DATAVIEW_KEYS: Record<string, TaskField> = {
  created: "created",
  start: "start",
  scheduled: "scheduled",
  due: "due",
  completion: "done",
  cancelled: "cancelled",
  priority: "priority",
  repeat: "recurrence",
};

const PRIORITY_WORDS: Record<string, Priority> = {
  highest: "highest",
  high: "high",
  medium: "medium",
  low: "low",
  lowest: "lowest",
};

const PRIORITY_EMOJI_CHAR: Record<Exclude<Priority, null>, string> = {
  highest: "🔺",
  high: "⏫",
  medium: "🔼",
  low: "🔽",
  lowest: "⏬",
};

const DATE_FIELD_EMOJI: Record<DateField, string> = {
  created: EMOJI_CREATED,
  start: EMOJI_START,
  scheduled: EMOJI_SCHEDULED,
  due: EMOJI_DUE,
  done: EMOJI_DONE,
  cancelled: EMOJI_CANCELLED,
};

const DATE_FIELD_DATAVIEW_KEY: Record<DateField, string> = {
  created: "created",
  start: "start",
  scheduled: "scheduled",
  due: "due",
  done: "completion",
  cancelled: "cancelled",
};

const FIELD_WORD_TO_CAMEL: Record<string, DateField> = {
  Created: "created",
  Start: "start",
  Scheduled: "scheduled",
  Due: "due",
  Done: "done",
  Cancelled: "cancelled",
};

const PRIORITY_WORD_TO_CAMEL: Record<string, Priority> = {
  Highest: "highest",
  High: "high",
  Medium: "medium",
  Low: "low",
  Lowest: "lowest",
  None: null,
};

const STATUS_TYPE_TO_CAMEL: Record<string, StatusType> = {
  TODO: "TODO",
  IN_PROGRESS: "IN_PROGRESS",
  ON_HOLD: "ON_HOLD",
  DONE: "DONE",
  CANCELLED: "CANCELLED",
  NON_TASK: "NON_TASK",
};

// --- Span management ---------------------------------------------------

/** Half-open byte range `[start, end)` into some larger string. Used by
 * the scanner to carry field/token positions back to callers; exported
 * so consumers (e.g. `lib/taskPreview.ts`) can derive chip text without
 * re-scanning. */
export interface Range {
  start: number;
  end: number;
}

function removeRanges(s: string, ranges: Range[]): string {
  if (ranges.length === 0) return s;
  const sorted = [...ranges].sort((a, b) => a.start - b.start);
  let out = "";
  let cursor = 0;
  for (const r of sorted) {
    const start = Math.max(r.start, cursor);
    if (start > cursor) out += s.slice(cursor, start);
    cursor = Math.max(cursor, r.end);
  }
  if (cursor < s.length) out += s.slice(cursor);
  return out;
}

function collapseWhitespace(s: string): string {
  return s.split(/\s+/).filter((x) => x.length > 0).join(" ");
}

// Mirrors Rust `char::is_alphanumeric()` (Unicode-aware). JS `\w`
// and `/[A-Za-z0-9_]/` are ASCII-only; the kernel's tag scanner
// recognises Hangul, CJK, etc. as word characters, so the mirror
// must agree or `findTagSpans` truncates at non-ASCII tag prefixes
// (the symptoms are: SetText on a Korean-tagged line drops the tag,
// `parseTaskLine.text` retains the tag bytes it should strip).
function isWordChar(c: string): boolean {
  if (c === "_") return true;
  return /[\p{L}\p{N}]/u.test(c);
}

/** Byte ranges of `#tag` runs in `s`, mirroring Rust's kernel tag
 * detector (Unicode-aware via `isWordChar`). Caller-relative positions.
 * Exported so sibling modules (e.g. `lib/taskPreview.ts`) can reuse the
 * single source of truth instead of re-scanning the line. */
export function tagSpansOf(s: string): Range[] {
  const spans: Range[] = [];
  let i = 0;
  while (i < s.length) {
    const ch = s[i];
    if (ch === "#") {
      const prev = i > 0 ? s[i - 1] : "";
      if (!isWordChar(prev)) {
        let j = i + 1;
        while (j < s.length && isWordChar(s[j])) j++;
        if (j > i + 1) {
          spans.push({ start: i, end: j });
          i = j;
          continue;
        }
      }
    }
    i++;
  }
  return spans;
}

function stripTagSpans(s: string): string {
  return removeRanges(s, tagSpansOf(s));
}

function mergeRanges(ranges: Range[]): Range[] {
  if (ranges.length === 0) return [];
  const sorted = [...ranges].sort((a, b) => a.start - b.start);
  const out: Range[] = [];
  for (const r of sorted) {
    const last = out[out.length - 1];
    if (last && r.start <= last.end) {
      last.end = Math.max(last.end, r.end);
    } else {
      out.push({ ...r });
    }
  }
  return out;
}

// --- Token scanner -----------------------------------------------------

interface ScanState {
  created: string | null;
  start: string | null;
  scheduled: string | null;
  due: string | null;
  done: string | null;
  cancelled: string | null;
  priority: Priority;
  recurrence: string | null;
  fieldSpans: Array<{ field: TaskField; range: Range }>;
}

function newState(): ScanState {
  return {
    created: null,
    start: null,
    scheduled: null,
    due: null,
    done: null,
    cancelled: null,
    priority: null,
    recurrence: null,
    fieldSpans: [],
  };
}

function scanContent(content: string, contentBase: number, state: ScanState): void {
  const len = content.length;
  let i = 0;
  let inCode = false;
  while (i < len) {
    const cp = content.codePointAt(i);
    if (cp === undefined) break;
    const cpLen = cp > 0xFFFF ? 2 : 1;
    const ch = String.fromCodePoint(cp);
    if (cp === "`".codePointAt(0)) {
      inCode = !inCode;
      i += cpLen;
      continue;
    }
    if (inCode) {
      i += cpLen;
      continue;
    }
    const rest = content.slice(i);
    if (rest.startsWith("](")) {
      // `closeRel` is measured AFTER the `](` prefix — the kernel strips
      // the prefix before searching (`after_link.find(')')`), so the
      // skip is exactly `](` + link text + `)`. Measuring from `rest`
      // instead overshoots by 2 and swallows the first field tokens
      // after the link.
      const closeRel = rest.slice(2).indexOf(")");
      if (closeRel >= 0) {
        i += 2 + closeRel + 1;
        continue;
      }
    }
    if (cp === "[".codePointAt(0)) {
      const afterBracket = rest.slice(1);
      const colonPos = afterBracket.indexOf("::");
      if (colonPos >= 0) {
        const key = afterBracket.slice(0, colonPos);
        if (key.length > 0 && /^[A-Za-z]+$/.test(key) && DATAVIEW_KEYS[key] !== undefined) {
          const field = DATAVIEW_KEYS[key];
          const afterColons = afterBracket.slice(colonPos + 2);
          const closeRel = afterColons.indexOf("]");
          if (closeRel >= 0) {
            const valueRaw = afterColons.slice(0, closeRel).trim();
            const tokenLen = 1 + colonPos + 2 + closeRel + 1;
            const range: Range = {
              start: contentBase + i,
              end: contentBase + i + tokenLen,
            };
            if (field === "priority") {
              state.priority = PRIORITY_WORDS[valueRaw.toLowerCase()] ?? null;
              state.fieldSpans.push({ field, range });
            } else if (field === "recurrence") {
              if (valueRaw.toLowerCase().startsWith("every")) {
                state.recurrence = valueRaw;
              }
              state.fieldSpans.push({ field, range });
            } else {
              const parsed = parseDateYyyyMmDd(valueRaw);
              if (parsed) {
                const iso = `${String(parsed.y).padStart(4, "0")}-${String(parsed.m).padStart(2, "0")}-${String(parsed.d).padStart(2, "0")}`;
                state[field as DateField] = iso;
              }
              state.fieldSpans.push({ field, range });
            }
            i += tokenLen;
            continue;
          }
        }
      }
    }
    const dateField = DATE_EMOJI_TO_FIELD[ch];
    if (dateField) {
      const markerLen = cpLen;
      let after = content.slice(i + markerLen);
      if (after.startsWith(VARIATION_SELECTOR_16)) {
        after = after.slice(VARIATION_SELECTOR_16.length);
      }
      let sepLen = 0;
      while (sepLen < after.length && (after[sepLen] === " " || after[sepLen] === NBSP)) {
        sepLen++;
      }
      const afterSep = after.slice(sepLen);
      let valueLen = 0;
      while (
        valueLen < afterSep.length &&
        afterSep[valueLen] !== " " &&
        afterSep[valueLen] !== "\t" &&
        afterSep[valueLen] !== NBSP
      ) {
        valueLen++;
      }
      const valueRaw = afterSep.slice(0, valueLen);
      const consumed = markerLen + sepLen + valueLen;
      const tokenLen = Math.max(consumed, markerLen);
      const range: Range = {
        start: contentBase + i,
        end: contentBase + i + tokenLen,
      };
      const parsed = parseDateYyyyMmDd(valueRaw);
      if (parsed) {
        const iso = `${String(parsed.y).padStart(4, "0")}-${String(parsed.m).padStart(2, "0")}-${String(parsed.d).padStart(2, "0")}`;
        state[dateField as DateField] = iso;
      }
      state.fieldSpans.push({ field: dateField, range });
      i += tokenLen;
      continue;
    }
    const prio = PRIORITY_EMOJI[ch];
    if (prio) {
      let totalLen = cpLen;
      if (content.slice(i + totalLen).startsWith(VARIATION_SELECTOR_16)) {
        totalLen += VARIATION_SELECTOR_16.length;
      }
      const range: Range = {
        start: contentBase + i,
        end: contentBase + i + totalLen,
      };
      state.priority = prio;
      state.fieldSpans.push({ field: "priority", range });
      i += totalLen;
      continue;
    }
    if (ch === EMOJI_RECURRENCE) {
      const markerLen = EMOJI_RECURRENCE.length;
      let after = content.slice(i + markerLen);
      if (after.startsWith(VARIATION_SELECTOR_16)) {
        after = after.slice(VARIATION_SELECTOR_16.length);
      }
      let sepLen = 0;
      while (sepLen < after.length && (after[sepLen] === " " || after[sepLen] === NBSP)) {
        sepLen++;
      }
      const afterSep = after.slice(sepLen);
      let valueLen = afterSep.length;
      for (let k = 0; k < afterSep.length; ) {
        const kcp = afterSep.codePointAt(k);
        if (kcp === undefined) break;
        const kcpLen = kcp > 0xFFFF ? 2 : 1;
        const kch = String.fromCodePoint(kcp);
        if (
          kch === "[" ||
          DATE_EMOJI_TO_FIELD[kch] !== undefined ||
          PRIORITY_EMOJI[kch] !== undefined ||
          kch === EMOJI_RECURRENCE
        ) {
          valueLen = k;
          break;
        }
        k += kcpLen;
      }
      const valueRaw = afterSep.slice(0, valueLen).trimEnd();
      const tokenLen = markerLen + sepLen + valueRaw.length;
      const range: Range = {
        start: contentBase + i,
        end: contentBase + i + tokenLen,
      };
      if (valueRaw.toLowerCase().startsWith("every")) {
        state.recurrence = valueRaw;
      }
      state.fieldSpans.push({ field: "recurrence", range });
      i += tokenLen;
      continue;
    }
    i += cpLen;
  }
}

/** Strict `YYYY-MM-DD` parser mirroring the kernel's
 * `parse_date_yyyy_mm_dd`: shape check plus real calendar validation
 * (`Date::from_calendar_date` rejects month 13, Feb 30, …). Exported so
 * chip rendering (`lib/taskPreview.ts`) applies the same validation the
 * kernel applies before trusting a date value. */
export function parseDateYyyyMmDd(s: string): { y: number; m: number; d: number } | null {
  const trimmed = s.trim();
  if (!/^\d{4}-\d{2}-\d{2}$/.test(trimmed)) return null;
  const y = +trimmed.slice(0, 4);
  const m = +trimmed.slice(5, 7);
  const d = +trimmed.slice(8, 10);
  // `daysInMonth` (recurrence section) implements the same month-length
  // table, leap years included, as `Date::from_calendar_date`.
  if (m < 1 || m > 12 || d < 1 || d > daysInMonth(y, m)) return null;
  return { y, m, d };
}

/** Recover the `Priority` value from a raw priority token: dataview
 * `[priority:: <word>]` first (it is the superset form — any bracketed
 * text fails the emoji branch), then a bare priority emoji, possibly
 * with the VS-16 suffix some editors insert. Unrecognised values —
 * e.g. `[priority:: none]` or an unknown word — collapse to `null`
 * ("no priority"). Exported so `lib/taskPreview.ts` derives chip
 * priority from the same tables the scanner reads; the priority
 * vocabulary lives in exactly one place. */
export function priorityFromFieldText(text: string): Priority {
  const m = /^\[\s*priority\s*::\s*([^\]]+?)\s*\]$/i.exec(text);
  if (m) {
    const word = (m[1] ?? "").toLowerCase();
    if (word === "none") return null;
    return PRIORITY_WORDS[word] ?? null;
  }
  return PRIORITY_EMOJI[text.replaceAll(VARIATION_SELECTOR_16, "")] ?? null;
}

// --- Checkbox prefix recognition ---------------------------------------

interface CheckboxPrefix {
  contentStart: number;
  symbol: string;
}

function recognizeCheckboxPrefix(afterIndent: string): CheckboxPrefix | null {
  if (afterIndent.length === 0) return null;
  const c0 = afterIndent[0];
  let markerLen: number;
  if (c0 === "-" || c0 === "*" || c0 === "+") {
    markerLen = 1;
  } else if (/[0-9]/.test(c0)) {
    let len = 1;
    let sawDelim = false;
    for (let idx = 1; idx < afterIndent.length; idx++) {
      const c = afterIndent[idx];
      if (/[0-9]/.test(c)) {
        len = idx + 1;
        continue;
      }
      if (c === "." || c === ")") {
        len = idx + 1;
        sawDelim = true;
      }
      break;
    }
    if (!sawDelim) return null;
    markerLen = len;
  } else {
    return null;
  }
  let rest = afterIndent.slice(markerLen);
  if (!rest.startsWith(" ")) return null;
  rest = rest.slice(1);
  if (!rest.startsWith("[")) return null;
  rest = rest.slice(1);
  if (rest.length === 0) return null;
  const sym = rest[0];
  rest = rest.slice(1);
  if (!rest.startsWith("]")) return null;
  rest = rest.slice(1);
  let contentStart: number;
  if (rest.startsWith(" ")) {
    contentStart = afterIndent.length - rest.length + 1;
  } else if (rest.length === 0) {
    contentStart = afterIndent.length;
  } else {
    return null;
  }
  return { contentStart, symbol: sym };
}

// --- parseTaskLine -----------------------------------------------------

export function parseTaskLine(raw: string, cfg: TaskLineCfg): ParsedLine | null {
  const table = buildStatusTable(cfg.statuses);
  let indentBytes = 0;
  while (indentBytes < raw.length && (raw[indentBytes] === " " || raw[indentBytes] === "\t")) {
    indentBytes++;
  }
  const trimmed = raw.slice(indentBytes);
  const prefix = recognizeCheckboxPrefix(trimmed);
  if (!prefix) return null;
  const checkboxRange: Range = {
    start: indentBytes,
    end: indentBytes + prefix.contentStart,
  };
  const content = trimmed.slice(prefix.contentStart);
  const contentBase = indentBytes + prefix.contentStart;

  const n = prefix.symbol === "X" ? "x" : prefix.symbol;
  const status = table.get(n) ?? { next: "x", type: "TODO" as StatusType };

  const state = newState();
  scanContent(content, contentBase, state);

  const removalRanges = state.fieldSpans.map((f) => ({
    start: f.range.start - contentBase,
    end: f.range.end - contentBase,
  }));
  const afterFields = collapseWhitespace(removeRanges(content, removalRanges));
  const text = collapseWhitespace(stripTagSpans(afterFields));

  return {
    symbol: n,
    statusType: status.type,
    text,
    spans: {
      checkbox: checkboxRange,
      fields: state.fieldSpans.map((f) => ({ field: f.field, start: f.range.start, end: f.range.end })),
    },
  };
}

// --- Token formatters --------------------------------------------------

/** Write the formatted token for a date field in the cfg's writeFormat
 *  (`📅 2026-08-27` for emoji, `[due:: 2026-08-27]` for dataview).
 *  Exported so `lib/taskSuggest.ts` and the §8 slash menu can reuse
 *  the single source of truth for the wire shape rather than
 *  re-implementing both formats. */
export function formatDateFieldToken(field: TaskField, iso: string, fmt: WriteFormat): string {
  if (fmt === "emoji") return `${DATE_FIELD_EMOJI[field as DateField]} ${iso}`;
  return `[${DATE_FIELD_DATAVIEW_KEY[field as DateField]}:: ${iso}]`;
}

/** The priority token in the cfg's write format (null clears the
 *  field). Exported for the §8 slash menu's option previews. */
export function formatPriorityToken(p: Priority, fmt: WriteFormat): string | null {
  if (p === null) return null;
  if (fmt === "emoji") return PRIORITY_EMOJI_CHAR[p];
  return `[priority:: ${p}]`;
}

/** The recurrence token in the cfg's write format. Exported for the
 *  §8 slash menu's option previews. */
export function formatRecurrenceToken(rule: string, fmt: WriteFormat): string {
  if (fmt === "emoji") return `${EMOJI_RECURRENCE} ${rule}`;
  return `[repeat:: ${rule}]`;
}

function renderNewTask(
  text: string,
  fields: {
    created: string | null;
    start: string | null;
    scheduled: string | null;
    due: string | null;
    priority: Priority;
    recurrence: string | null;
    tags: string[];
  },
  cfg: TaskLineCfg,
): string {
  if (text.includes("\n") || text.includes("\0")) {
    throw new Error("task text must not contain newline or NUL");
  }
  let line = "- [ ] ";
  line += text;
  for (const tag of fields.tags) line += ` #${tag}`;
  if (cfg.globalFilter.length > 0) line += ` ${cfg.globalFilter}`;
  const dateFields: Array<[DateField, string | null]> = [
    ["created", fields.created],
    ["start", fields.start],
    ["scheduled", fields.scheduled],
    ["due", fields.due],
  ];
  for (const [field, value] of dateFields) {
    if (value) line += ` ${formatDateFieldToken(field, value, cfg.writeFormat)}`;
  }
  const ptoken = formatPriorityToken(fields.priority, cfg.writeFormat);
  if (ptoken) line += ` ${ptoken}`;
  if (fields.recurrence) line += ` ${formatRecurrenceToken(fields.recurrence, cfg.writeFormat)}`;
  return line;
}

function spliceFieldOps(
  raw: string,
  fieldSpans: Array<{ field: TaskField; start: number; end: number }>,
  ops: Array<{ field: TaskField; token: string | null }>,
): string {
  const remove: Range[] = [];
  for (const op of ops) {
    for (const f of fieldSpans) {
      if (f.field === op.field) remove.push({ start: f.start, end: f.end });
    }
  }
  let out = removeRanges(raw, remove);
  for (const op of ops) {
    if (op.token === null) continue;
    if (out.length > 0 && !out.endsWith(" ")) out += " ";
    out += op.token;
  }
  return out;
}

function replaceSymbol(
  raw: string,
  spans: { checkbox: Range },
  newSymbol: string,
): string {
  if (/[\n\r\0\[\]]/.test(newSymbol)) {
    throw new Error("status symbol must not be newline, NUL, or a bracket");
  }
  const cb = raw.slice(spans.checkbox.start, spans.checkbox.end);
  const bracketRel = cb.indexOf("[");
  const symStart = spans.checkbox.start + bracketRel + 1;
  const symEnd = symStart + 1; // single BMP code unit (kernel normalizes X -> x)
  return raw.slice(0, symStart) + newSymbol + raw.slice(symEnd);
}

// --- Recurrence -------------------------------------------------------

interface RecurrenceSpec {
  calendarMonths: number;
  fixedMillis: number;
  whenDone: boolean;
}

const DAY_MS = 86_400_000;

function parseRecurrenceSpec(rule: string): RecurrenceSpec | null {
  const trimmed = rule.trim();
  const lower = trimmed.toLowerCase();
  const tokens = lower.split(/\s+/).filter((t) => t.length > 0);
  if (tokens.length === 0 || tokens[0] !== "every") return null;
  let whenDone = false;
  let work = tokens;
  if (
    work.length >= 3 &&
    work[work.length - 2] === "when" &&
    work[work.length - 1] === "done"
  ) {
    whenDone = true;
    work = work.slice(0, -2);
  }
  const rest = work.slice(1);
  let n = 1;
  let unit: string;
  if (rest.length === 1) {
    unit = rest[0];
  } else if (rest.length === 2) {
    const parsed = Number(rest[0]);
    if (!Number.isFinite(parsed) || parsed <= 0 || !Number.isInteger(parsed)) return null;
    n = parsed;
    unit = rest[1];
  } else {
    return null;
  }
  switch (unit) {
    case "day":
    case "days":
      return { calendarMonths: 0, fixedMillis: n * DAY_MS, whenDone };
    case "week":
    case "weeks":
      return { calendarMonths: 0, fixedMillis: n * 7 * DAY_MS, whenDone };
    case "month":
    case "months":
      return { calendarMonths: n, fixedMillis: 0, whenDone };
    case "year":
    case "years":
      return { calendarMonths: n * 12, fixedMillis: 0, whenDone };
  }
  return null;
}

function dateAdd(iso: string, spec: RecurrenceSpec): string {
  const parsed = parseDateYyyyMmDd(iso);
  if (!parsed) throw new Error("invalid date");
  if (spec.calendarMonths !== 0) {
    return addCalendarMonths(parsed.y, parsed.m, parsed.d, spec.calendarMonths);
  }
  const dt = new Date(Date.UTC(parsed.y, parsed.m - 1, parsed.d));
  dt.setUTCDate(dt.getUTCDate() + spec.fixedMillis / DAY_MS);
  return `${dt.getUTCFullYear()}-${String(dt.getUTCMonth() + 1).padStart(2, "0")}-${String(dt.getUTCDate()).padStart(2, "0")}`;
}

function addCalendarMonths(y: number, m: number, d: number, delta: number): string {
  const total = y * 12 + (m - 1) + delta;
  const newY = Math.floor(total / 12);
  const newM = (total % 12) + 1;
  const dim = daysInMonth(newY, newM);
  const newD = Math.min(d, dim);
  return `${newY}-${String(newM).padStart(2, "0")}-${String(newD).padStart(2, "0")}`;
}

function daysInMonth(y: number, m: number): number {
  switch (m) {
    case 1:
    case 3:
    case 5:
    case 7:
    case 8:
    case 10:
    case 12:
      return 31;
    case 4:
    case 6:
    case 9:
    case 11:
      return 30;
    case 2:
      return (y % 4 === 0 && y % 100 !== 0) || y % 400 === 0 ? 29 : 28;
    default:
      return 30;
  }
}

function shiftDate(iso: string, days: number): string {
  const parsed = parseDateYyyyMmDd(iso);
  if (!parsed) throw new Error("invalid date");
  const dt = new Date(Date.UTC(parsed.y, parsed.m - 1, parsed.d));
  dt.setUTCDate(dt.getUTCDate() + days);
  return `${dt.getUTCFullYear()}-${String(dt.getUTCMonth() + 1).padStart(2, "0")}-${String(dt.getUTCDate()).padStart(2, "0")}`;
}

function daysBetween(a: string, b: string): number {
  const ap = parseDateYyyyMmDd(a);
  const bp = parseDateYyyyMmDd(b);
  if (!ap || !bp) throw new Error("invalid date");
  const ad = Date.UTC(ap.y, ap.m - 1, ap.d);
  const bd = Date.UTC(bp.y, bp.m - 1, bp.d);
  return Math.round((bd - ad) / DAY_MS);
}

/** Pure preview used by `TaskEditPopover` (Plan C Task 9): given a
 * recurrence rule and an anchor date, return the next ISO occurrence
 * (`YYYY-MM-DD`). `todayISO` matters for "every N when done" rules,
 * which advance from today rather than the stale anchor — that matches
 * the kernel's `transform_task_draft` recurrence spawn branch
 * (uses `anchorDate = whenDone ? today : anchor`).
 *
 * Returns `null` for:
 *   • an empty / unparseable rule (caller hides the preview), OR
 *   • a parseable rule with no usable anchor (caller shows
 *     `task_recurrence_needs_date`).
 *
 * The popover composes the two signals by branching on null vs
 * string — no separate "invalid"/"no-anchor" enum needed. */
export function nextOccurrencePreview(
  ruleISO: string,
  anchorISO: string | null,
  todayISO: string | null,
): string | null {
  const spec = parseRecurrenceSpec(ruleISO);
  if (!spec) return null;
  const anchor = spec.whenDone ? todayISO : anchorISO;
  if (!anchor) return null;
  return dateAdd(anchor, spec);
}

function indentColumnsOf(raw: string): number {
  let cols = 0;
  for (let i = 0; i < raw.length; i++) {
    const ch = raw[i];
    if (ch === " ") cols++;
    else if (ch === "\t") cols = (Math.floor(cols / 4) + 1) * 4;
    else break;
  }
  return cols;
}

// --- transformTaskDraft -----------------------------------------------

export function transformTaskDraft(
  body: string,
  line: number,
  edit: TaskEdit,
  todayISO: string,
  cfg: TaskLineCfg,
): { changes: TaskLineChange[] } {
  const table = buildStatusTable(cfg.statuses);
  if (!parseDateYyyyMmDd(todayISO)) throw new Error("todayISO must be YYYY-MM-DD");
  const lines = body.split(/\r?\n/);
  const raw = lines[line];
  if (raw === undefined) throw new Error(`line ${line} out of range`);
  const parsed = parseTaskLine(raw, cfg);
  if (!parsed) throw new Error(`line ${line} is not a task line`);

  const aux = extractAuxFields(raw, parsed);

  if (edit.kind === "text") {
    return { changes: [{ start_line: line, delete_lines: 1, insert_lines: [setText(raw, parsed, edit.value, cfg)] }] };
  }

  if (edit.kind === "date") {
    const token = edit.value ? formatDateFieldToken(edit.field, edit.value, cfg.writeFormat) : null;
    const newLine = spliceFieldOps(raw, parsed.spans.fields, [{ field: edit.field, token }]);
    return { changes: [{ start_line: line, delete_lines: 1, insert_lines: [newLine] }] };
  }
  if (edit.kind === "priority") {
    const token = formatPriorityToken(edit.value, cfg.writeFormat);
    const newLine = spliceFieldOps(raw, parsed.spans.fields, [{ field: "priority", token }]);
    return { changes: [{ start_line: line, delete_lines: 1, insert_lines: [newLine] }] };
  }

  if (edit.kind === "recurrence") {
    const token = edit.value ? formatRecurrenceToken(edit.value, cfg.writeFormat) : null;
    const newLine = spliceFieldOps(raw, parsed.spans.fields, [{ field: "recurrence", token }]);
    return { changes: [{ start_line: line, delete_lines: 1, insert_lines: [newLine] }] };
  }

  // status / toggle
  const newSymbol =
    edit.kind === "toggle"
      ? (table.get(parsed.symbol) ?? { next: "x", type: "TODO" as StatusType }).next
      : edit.symbol;
  if (/[\n\r\0\[\]]/.test(newSymbol)) {
    throw new Error("status symbol must not be newline, NUL, or a bracket");
  }
  const newType = (table.get(newSymbol === "X" ? "x" : newSymbol) ?? { next: "x", type: "TODO" as StatusType }).type;
  const oldType = parsed.statusType;
  const oldIsTerminal = oldType === "DONE" || oldType === "CANCELLED";
  const newIsTerminal = newType === "DONE" || newType === "CANCELLED";

  if (oldType === newType) {
    const newLine = replaceSymbol(raw, parsed.spans, newSymbol);
    return { changes: [{ start_line: line, delete_lines: 1, insert_lines: [newLine] }] };
  }

  let lineBuf = raw;
  let spawnLine: string | null = null;

  if (newIsTerminal) {
    const stampField: DateField = newType === "DONE" ? "done" : "cancelled";
    const clearField: DateField = newType === "DONE" ? "cancelled" : "done";
    const stampToken = formatDateFieldToken(stampField, todayISO, cfg.writeFormat);
    lineBuf = spliceFieldOps(raw, parsed.spans.fields, [
      { field: stampField, token: stampToken },
      { field: clearField, token: null },
    ]);
    if (newType === "DONE" && !oldIsTerminal && aux.recurrence) {
      const spec = parseRecurrenceSpec(aux.recurrence);
      if (spec) {
        const anchor = aux.due ?? aux.scheduled ?? aux.start;
        if (anchor) {
          const anchorDate = spec.whenDone ? todayISO : anchor;
          const newAnchor = dateAdd(anchorDate, spec);
          // Kernel computes delta = new_anchor - ORIGINAL anchor (not
          // anchor_date), so a `when done` rule whose original anchor
          // is older than today yields a positive shift that lands
          // every shifted date forward by (new_anchor - original).
          const delta = daysBetween(anchor, newAnchor);
          const shiftedDue = aux.due ? shiftDate(aux.due, delta) : null;
          const shiftedScheduled = aux.scheduled ? shiftDate(aux.scheduled, delta) : null;
          const shiftedStart = aux.start ? shiftDate(aux.start, delta) : null;
          const spawned = renderNewTask(
            aux.text,
            {
              created: aux.created,
              start: shiftedStart,
              scheduled: shiftedScheduled,
              due: shiftedDue,
              priority: aux.priority,
              recurrence: aux.recurrence,
              tags: aux.tags,
            },
            cfg,
          );
          // Override the default TODO symbol with the first configured one
          // (the kernel calls `first_todo_symbol`; render_new_task
          // emits "- [ ]" with the literal space, so we substitute here).
          const todoSym = firstTodoSymbol(cfg.statuses);
          spawnLine = spawned.replace(/^- \[ \]/, `- [${todoSym}]`);
        }
      }
    }
  } else if (oldIsTerminal) {
    const clearField: DateField = oldType === "DONE" ? "done" : "cancelled";
    lineBuf = spliceFieldOps(raw, parsed.spans.fields, [{ field: clearField, token: null }]);
  }

  const newLine = replaceSymbol(lineBuf, parsed.spans, newSymbol);
  if (!spawnLine) {
    return { changes: [{ start_line: line, delete_lines: 1, insert_lines: [newLine] }] };
  }
  if (cfg.recurrenceInsert === "above") {
    return {
      changes: [
        {
          start_line: line,
          delete_lines: 1,
          insert_lines: [spawnLine, newLine],
        },
      ],
    };
  }
  // below: scan forward for children, insert after the subtree
  const deletedIndent = indentColumnsOf(raw);
  let end = line + 1;
  while (end < lines.length) {
    const nextRaw = lines[end];
    if (indentColumnsOf(nextRaw) <= deletedIndent) break;
    end++;
  }
  return {
    changes: [
      { start_line: line, delete_lines: 1, insert_lines: [newLine] },
      { start_line: end, delete_lines: 0, insert_lines: [spawnLine] },
    ],
  };
}

/** First configured symbol of a status type (built-ins first, custom
 *  `[tasks.statuses]` entries layered on top — the same table
 *  `transformTaskDraft` resolves symbols through). The §8 slash menu
 *  uses it to promote a plain line to a TODO/IN_PROGRESS task with the
 *  vault's own symbols, never a hardcoded one. */
export function symbolForStatusType(cfg: TaskLineCfg, type: StatusType): string {
  const table = buildStatusTable(cfg.statuses);
  for (const [sym, entry] of table) {
    if (entry.type === type) return sym;
  }
  return " ";
}

function firstTodoSymbol(defs: StatusDef[]): string {
  const table = buildStatusTable(defs);
  for (const [sym, entry] of table) {
    if (entry.type === "TODO") return sym;
  }
  return " ";
}

export function extractAuxFields(
  raw: string,
  parsed: ParsedLine,
): {
  text: string;
  tags: string[];
  created: string | null;
  start: string | null;
  scheduled: string | null;
  due: string | null;
  done: string | null;
  cancelled: string | null;
  priority: Priority;
  recurrence: string | null;
} {
  const state = newState();
  const contentStart = parsed.spans.checkbox.end;
  scanContent(raw.slice(contentStart), contentStart, state);
  // Tags live in the field-stripped content BEFORE tag stripping — the
  // kernel computes `extract_tags(&after_fields)` (tasks.rs parse body)
  // and only then strips them from the description. Scanning
  // `parsed.text` (already stripped) always yielded [].
  const content = raw.slice(contentStart);
  const removal = parsed.spans.fields.map((f) => ({
    start: f.start - contentStart,
    end: f.end - contentStart,
  }));
  const afterFields = collapseWhitespace(removeRanges(content, removal));
  const tags = tagSpansOf(afterFields).map((r) => afterFields.slice(r.start + 1, r.end));
  return {
    text: parsed.text,
    tags,
    created: state.created,
    start: state.start,
    scheduled: state.scheduled,
    due: state.due,
    done: state.done,
    cancelled: state.cancelled,
    priority: state.priority,
    recurrence: state.recurrence,
  };
}

function setText(raw: string, parsed: ParsedLine, newText: string, cfg: TaskLineCfg): string {
  if (newText.includes("\n") || newText.includes("\0")) {
    throw new Error("task text must not contain newline or NUL");
  }
  const contentStart = parsed.spans.checkbox.end;
  const content = raw.slice(contentStart);
  const contentTags = tagSpansOf(content);
  const tagRanges: Range[] = contentTags.map((r) => ({
    start: r.start + contentStart,
    end: r.end + contentStart,
  }));
  const kept: Range[] = parsed.spans.fields.map((f) => ({ start: f.start, end: f.end }));
  kept.push(...tagRanges);
  if (cfg.globalFilter.length > 0) {
    const pos = content.indexOf(cfg.globalFilter);
    if (pos >= 0) {
      kept.push({
        start: pos + contentStart,
        end: pos + contentStart + cfg.globalFilter.length,
      });
    }
  }
  const merged = mergeRanges(kept);
  let out = raw.slice(0, contentStart);
  out += newText;
  for (const r of merged) {
    out += " ";
    out += raw.slice(r.start, r.end);
  }
  return out;
}

// --- Adapters from the externally-tagged JSON the Rust emitter writes ---
//
// Rust serializes `TaskEdit` (no `Serialize` derive on the kernel type,
// so the fixture emitter hand-builds each variant) as:
//
//   "Toggle"
//   { "SetStatus": "x" }
//   { "SetDate":   { "field": "Due",      "value": "2026-08-30" } }
//   { "SetPriority": "high" }
//   { "SetText":   "new text" }
//   { "SetRecurrence": "every week" }
//   { "SetRecurrence": null }
//   "Delete"
//
// TS mirrors with camelCase discriminated unions (`{ kind, ... }`).
// These two adapters keep the wire shape and the mirror shape in
// lockstep without forcing one to bow to the other.

export interface WireTaskEdit {
  Toggle?: null;
  SetStatus?: string;
  SetDate?: { field: string; value: string | null };
  SetPriority?: string;
  SetText?: string;
  SetRecurrence?: string | null;
  Delete?: null;
}

export function editFromJson(json: string | WireTaskEdit): TaskEdit {
  if (typeof json === "string") {
    if (json === "Toggle") return { kind: "toggle" };
    if (json === "Delete") throw new Error("TaskEdit::Delete is out of mirror scope");
    throw new Error(`unrecognized edit string: ${json}`);
  }
  if ("Toggle" in json && json.Toggle === undefined) return { kind: "toggle" };
  if ("Delete" in json && json.Delete === undefined) {
    throw new Error("TaskEdit::Delete is out of mirror scope");
  }
  if (json.SetStatus !== undefined) return { kind: "status", symbol: json.SetStatus };
  if (json.SetDate !== undefined) {
    const f = FIELD_WORD_TO_CAMEL[json.SetDate.field];
    if (!f) throw new Error(`unknown DateField ${json.SetDate.field}`);
    return { kind: "date", field: f, value: json.SetDate.value };
  }
  if (json.SetPriority !== undefined) {
    if (!(json.SetPriority in PRIORITY_WORD_TO_CAMEL)) {
      throw new Error(`unknown priority ${json.SetPriority}`);
    }
    return { kind: "priority", value: PRIORITY_WORD_TO_CAMEL[json.SetPriority] };
  }
  if (json.SetText !== undefined) return { kind: "text", value: json.SetText };
  if (json.SetRecurrence !== undefined) {
    return { kind: "recurrence", value: json.SetRecurrence };
  }
  throw new Error(`unrecognized edit JSON: ${JSON.stringify(json)}`);
}
export interface WireTaskStatusDef {
  symbol: string;
  type: string;
  next: string;
}

export interface WireTaskLineCfg {
  write_format: WriteFormat;
  global_filter: string;
  recurrence_insert: RecurrenceInsert;
  statuses: WireTaskStatusDef[];
  // The Rust cfg has more fields (capture_target, default_section,
  // enabled) but the mirror doesn't need them — accept and ignore.
  capture_target?: string;
  default_section?: string;
  enabled?: boolean;
}

export function cfgFromJson(json: WireTaskLineCfg): TaskLineCfg {
  return {
    writeFormat: json.write_format,
    globalFilter: json.global_filter,
    recurrenceInsert: json.recurrence_insert,
    statuses: json.statuses.map((s) => ({
      symbol: s.symbol,
      type: STATUS_TYPE_TO_CAMEL[s.type] ?? "TODO",
      next: s.next,
    })),
  };
}